#::PROJECT:CI:NGINX-SLIM
default:
  image: wyga/docker-shell:latest
  services:
    - docker:dind
  tags:
    - docker-in-docker

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CREATE_CONTEXT: 1

stages:
  - builder

Image Builder:
  stage: builder
  variables:
    GIT_DEPTH: 1
  before_script:
    - ci/ci-setup-environment
  script:
    - ./ci-builder
  artifacts:
    name: "build-artifacts-${CI_PROJECT_NAME}"
    paths:
      - .artifacts
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG =~ /trigger/
